//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "apistats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub daily_count: i32,
    pub total_count: i32,
    pub apilist_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::apilist::Entity",
        from = "Column::ApilistId",
        to = "super::apilist::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Apilist,
}

impl Related<super::apilist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Apilist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
