//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::aerich::Entity as Aerich;
pub use super::apilist::Entity as Apilist;
pub use super::apistats::Entity as Apistats;
pub use super::data_cos_image::Entity as DataCosImage;
pub use super::data_cos_video::Entity as DataCosVideo;
pub use super::friend_links::Entity as FriendLinks;
