name: Build and Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add MUSL target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Build (static)
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: axum-binary
        path: target/x86_64-unknown-linux-musl/release/xuul
