name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Run Tests
        run: cargo test --release

      - name: Archive Release Binary
        if: success()
        run: |
          mkdir -p dist
          cp target/release/xuul dist/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-binary
          path: dist/
